Makefile.thirdparty

“kyotocabinet” does not exist in “thirdparty” directory.

remove unused instructions

---

src/gear/charset_filter.cc

according to http://unicode.org/roadmaps/sip/, CJK Compatibility Ideographs Supplement(0002F800-0002FA1F) was also included in Plane 2.

add other SIP Characters into charset_filter

---

include/rime_api.h
src/rime_api.cc

增加了 #57 提到的自定義選擇標籤的功能。 
@lotem 
幫忙看看：
char **的用法，二維數組的大小用的是page_size。
librime以及前端如何兼容舊版。

Issue #57: add menu/alternative_select_labels

---

build.bat

修正目前的版本中编译报错的问题.
1. 编译 `boost` 时增加 `locale` 模块.
2. 在 `PATH` 中增加  `CMAKE_INSTALL_PATH`.

Add --with-locale/CMAKE_INSTALL_PATH

---

appveyor.install.bat
appveyor.yml
build.bat

[![Build status](https://ci.appveyor.com/api/projects/status/hljcqan6416uakiw/branch/appveyor-ci?svg=true)](https://ci.appveyor.com/project/jakwings/librime/branch/appveyor-ci)
It is a time-consuming task:
* [build without caching thirdparty libraries](https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%209): ~25 minutes
* [build with cache](https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%2010): ~12 minutes

Set up Appveyor CI for Windows platform

---

Makefile.xcode

This bug causes the invalid cache problem in rime/squirrel#99.

(build) typos

---

appveyor.yml

This commit makes AppVeyor CI export built binaries in .zip format after every successful build.
An example is accessible via this [link](https://ci.appveyor.com/api/buildjobs/k1n8jxgbdylrmlix/artifacts/rime.zip).

Package artifacts on AppVeyor CI.

---

src/gear/key_binder.cc

- { when: always, accept: Control+g,  set: ascii_mode}
- { when: always, accept: Control+g,  unset: ascii_mode}
- { when: always, accept: Control+g,  toggle: ascii_mode}

support set and unset option in key_binder

---

appveyor.install.bat
appveyor.yml

* Now artifacts consists of minimal files needed for Weasel build.
* Use `appveyor DownloadFile` instead of curl, since curl on AppVeyor doesn't support HTTPS.

Add includes and OpenCC data into AppVeyor CI artifacts.

---

include/rime/gear/history_translator.h
src/gear/gears_module.cc
src/gear/history_translator.cc

history_translator@history
history:
input: ls
size: 1
initial_quality: 1000

feat(translator): add history_translator

---

data/test/config_compiler_test.yaml
src/rime/config/config_compiler.cc
src/rime/config/config_compiler.h
src/rime/config/config_component.cc
test/config_compiler_test.cc
test/config_test.cc

config: support optional references; fix auto saving

---

data/test/config_compiler_test.yaml
data/test/config_dependency_test.yaml
data/test/config_merge_test.yaml
data/test/config_optional_reference_test.yaml
data/test/starcraft.yaml
src/rime/config/config_compiler.cc
src/rime/config/config_compiler.h
src/rime/config/config_data.cc
src/rime/config/config_types.h
test/CMakeLists.txt
test/config_compiler_test.cc

usage:
```yaml
schema_list:
__include: default:/schema_list
__append:
- excited
- too young
punctuator:
__include: default:/punctuator
half_shape: # '/+' is optional after a key in merged map
'.' : '.'
'-' : ['-', '--'] # overwriting
'*' : {__append: ['*-*', '*<*>*']}
key_binder:
__include: default:/key_binder
bindings/+: # '/+' is required for appending to a list
- {key: one more}
- {key: two more}
__patch:
schema_list/+:
- sometimes
- naive
punctuator/half_shape/+:
'.' : '...'
punctuator/full_shape/=: {}
key_binder/bindings:
- {key: the only one}
```

config: support append and merge syntax

---

src/rime/config/auto_patch_config_plugin.cc
src/rime/config/config_compiler.cc
src/rime/config/config_compiler.h
src/rime/config/config_compiler_impl.h
src/rime/config/config_component.cc
src/rime/config/config_component.h
src/rime/config/config_cow_ref.h
src/rime/config/config_data.cc
src/rime/config/legacy_dictionary_config_plugin.cc
src/rime/config/legacy_preset_config_plugin.cc
src/rime/config/plugins.h
src/rime/core_module.cc
src/rime/gear/key_binder.cc
src/rime/gear/punctuator.cc
src/rime/gear/punctuator.h
src/rime/gear/recognizer.cc
src/rime/lever/customizer.cc
src/rime/lever/customizer.h
src/rime/lever/deployment_tasks.cc

Fixes #149 , also:
- Fixed two bugs in config dependency resolution append/merge algorithm.
- Disabled the old Customizer.
TODO:
- Remove the patched copy on next upgrade.
- Schema copied to user direction without notification, as well as symlinks should be removed too,
- after applying the fallback resource resolver to dictionary files.

feat(config): config compiler plugins for auto-patching and supporting legacy import_preset syntax

---

CMakeLists.txt
appveyor.yml
src/rime/algo/algebra.h
src/rime/algo/calculus.h
src/rime/algo/encoder.h
src/rime/algo/syllabifier.h
src/rime/config/config_component.h
src/rime/config/config_types.h
src/rime/dict/db.h
src/rime/dict/dict_compiler.h
src/rime/dict/dictionary.h
src/rime/dict/mapped_file.h
src/rime/dict/prism.h
src/rime/dict/table.h
src/rime/dict/text_db.h
src/rime/dict/user_db.h
src/rime/engine.h
src/rime/key_event.h
src/rime/key_table.cc
src/rime/key_table.h
src/rime/menu.h
src/rime/registry.h
src/rime/resource.h
src/rime/segmentation.h
src/rime/setup.cc
src/rime/setup.h
src/rime/ticket.h
src/rime/translation.h
test/CMakeLists.txt
test/resource_resolver_test.cc

This pull request replaces #151, avoiding two drawbacks from the previous solution:
1. The previous approach required CMake 3.4, which was not provided in Travis CI build environment.
2. Exporting all symbols would increase the DLL size significantly.
This commit utilizes `target_compile_definitions`, introduced in CMake 2.8.11.

chore(rime_test): link with Windows DLL

---

data/test/config_circular_dependency_test.yaml
src/rime/config/config_compiler.cc
test/config_compiler_test.cc

to fix the reported issue in https://github.com/rime/librime/pull/150#issuecomment-330421208

feat(config): best effort resolution for circurlar dependencies

---

src/rime/algo/calculus.cc
src/rime/gear/recognizer.cc

fix(calculus, recognizer): memory leak due to unchecked regex error

---

CMakeLists.txt
src/rime/config/build_info_plugin.cc
src/rime/config/config_compiler.cc
src/rime/config/config_compiler.h
src/rime/config/config_component.cc
src/rime/config/config_component.h
src/rime/config/config_data.cc
src/rime/config/config_data.h
src/rime/config/plugins.h
src/rime/config/save_output_plugin.cc
src/rime/core_module.cc
src/rime/dict/dict_compiler.cc
src/rime/dict/dict_compiler.h
src/rime/dict/dictionary.cc
src/rime/dict/reverse_lookup_dictionary.cc
src/rime/lever/deployment_tasks.cc
src/rime/lever/deployment_tasks.h
src/rime/lever/levers_module.cc
src/rime/schema.h
src/rime/switcher.cc
src/rime_api.cc
src/rime_api.h
test/config_compiler_test.cc
test/config_test.cc

These changes aim to fix #164, fix rime/weasel#99, fix osfans/PRIME#30, and close rime/ibus-rime#37.
Used to compare the checksum of $user_data_dir/default.yaml, but the file is now optional.
Detection for changes in YAML (could invalidate *.prism.bin) is now broken by cross-file YAML references. It requires all contents are gathered into the checksummed file.

WIP feature: relocate built config/dictionary files to $user_data_dir/build

---

.gitignore
.npmrc
CHANGELOG.md
package.json

這個生成器只摘抄了 GitHub 上的 Issues / PR 動態。
因爲最近的衆多提交已經採用 conventional changelog，我想根據 commit message 生成 CHANGELOG 更合適。可我還沒時間試用相關工具，又怕因爲提交粒度不合適、自動生成的 log 詳略不當。有時間再研究。

chore(CHANGELOG.md): auto-generate conventional changelog

---

src/rime/dict/level_db.cc
src/rime/dict/user_db.cc
src/rime/dict/user_db.h
src/rime/lever/user_dict_manager.cc

Fixes #188: UserDbFormat<BaseDb>::extension not working

fix(user_db): unwanted implicit instantiation of UserDbFormat template

---

src/rime/config/config_compiler.cc
src/rime/config/config_data.cc

fix(config_compiler): "/" mistaken as path separator in merged map key

---

src/rime/lever/deployment_tasks.cc

Issue fixed:
Updating weasel 0.9 to 0.10.0, found remaining YAML files (not patched) copied to user directory by weasel 0.9; end up using older version of Rime schemata.
Those files are meant to be moved to trash/. However librime 1.3 takes a more conservative move, only trashing patched YAML files.

fix(config_file_update): clean up deprecated user copy

---

CMakeLists.txt
src/rime/engine.cc

内置ENABLE_ASAN选项，方便开启[Address Sanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer)内存检测～
加上ASAN_OPTIONS=abort_on_error=1环境变量在调试时遇到内存问题则会断下来，
印象Windows版Clang还不能用这功能，我没还加平台宏，你们看看有没有必要。
另外，我简单测了下rime_api_console，发现报出一个问题（输入test，选“特色”），你们看看我这样改的是不是你们所期望的～

Add Address Sanitizer support

---

src/rime/gear/table_translator.cc

fix(table_translator): enable encoding uniquified commit history

---

Dockerfile

#234 
We wrap the build steps of librime into a Dockerfile.
Hope it helps.

+ Dockerfile for build

---

src/rime/dict/dictionary.cc
src/rime/dict/dictionary.h
src/rime/gear/reverse_lookup_translator.cc
src/rime/gear/script_translator.cc
src/rime/gear/table_translator.cc
src/rime/gear/table_translator.h
test/dictionary_test.cc
test/generate_pinyin_initials.js

measure performance:
```bash
cd librime
make
(cd build/bin; echo | ./rime_console)  # build data
node test/generate_pinyin_initials.js 512 > build/bin/input.txt
(cd build/bin; time ./rime_console < input.txt > output.txt)
```
compared to `master` version, conversion of long pinyin initial sequence is about 10% faster.

perf(dictionary): refactor DictEntryIterator and do partial sort

---

src/rime/dict/dict_compiler.cc
src/rime/dict/dict_settings.cc
src/rime/dict/dict_settings.h
src/rime/dict/entry_collector.cc
src/rime/dict/preset_vocabulary.cc
src/rime/dict/preset_vocabulary.h

the new settings item `vocabulary: essay` is equivalent to `use_preset_vocabulary: true`.
this commit enables changing `essay` to a user specified vocabulary db eg. `essay-zh-hans`.

feat(dict): specify vocabulary db name in dict settings

---

src/rime/commit_history.h
src/rime/composition.cc
src/rime/composition.h
src/rime/gear/contextual_translation.cc
src/rime/gear/contextual_translation.h
src/rime/gear/poet.cc
src/rime/gear/poet.h
src/rime/gear/script_translator.cc
src/rime/gear/script_translator.h
src/rime/gear/table_translator.cc
src/rime/gear/table_translator.h
src/rime/gear/translator_commons.cc
src/rime/gear/translator_commons.h

Closes #99
Usage:
with `script_translator`:
```yaml
patch:
grammar:
language: zh-hant-t-essay-bgw
translator/contextual_suggestions: true
translator/max_homophones: 7
```
with `table_translator`:
```yaml
patch:
grammar:
language: zh-hant-t-essay-bgc
collocation_max_length: 2
collocation_min_length: 2
translator/contextual_suggestions: true
translator/max_homographs: 5
```

 feat(translator): contextual suggestions

---

CMakeLists.txt

Force Boost.Uuid to use obsolete CryptoAPI for Windows XP compatibility, as the new Cryptography API: Next Generation (CNG) requires minimum version of Windows Vista.

fix(cmake): libboost Windows XP compatibility fix

---

src/rime/gear/charset_filter.cc
src/rime/gear/charset_filter.h
test/charset_filter_test.cc

通过配置 charset_filter 为 'gb2312+emoji' 方式允许 Emoji 出现在特定 charset。
Emoji 数据源来自于：https://github.com/rhdunn/espeak/blob/master/dictsource/en_emoji
相关 PR https://github.com/rime/librime/pull/213
配置范例：
```yaml
switches:
...
- options: [gb2312+emoji, gbk+emoji, utf8]
states:
- GB2312
- GBK
- UTF-8
reset: 0
engine/filters:
...
- simplifier
- charset_filter@gb2312+emoji
- charset_filter@gbk+emoji
...
```

feat: chareset_filter allow emoji with option

---

src/rime/gear/charset_filter.cc
test/charset_filter_test.cc

upgrade emoji match: use emoji 12.0 data, data via http://www.unicode.org/Public/emoji/12.0/emoji-data.txt.

fix: use official emoji 12.0 data

---

CMakeLists.txt

Debian's packger of librime here. This patch would introduce the GNUInstallDirs module into the project's top-level CMakeLists.txt.
[GNUInstalldirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) is available since CMake 3.0.2. It provides standard install directory variables as defined for GNU software. Using this module would provides standard variable names for bindir, libdir, includedir and datadir, etc., which would be beneficial. There's no needs for manual string concatenation anymore.
This module is especially useful for Debian-based Linux distributions since they are using `/usr/lib/<arch-triplet>/` as libdir instead of `/usr/lib/` and `/usr/lib64/`. The GNUInstallDirs module can elegantly suit such needs.
CMake >= 3.0.2 has been available for many years. It is at …

CMakeLists.txt: Use GNUinstalldirs module

---

CMakeLists.txt

This fixes the regression introduced in the last commit. The `${CMAKE_INSTALL_*DIR}` variables are not absolute and we must prepend them with `${prefix}` or `${exec_prefix}` to make it fully working.
There are also `${CMAKE_INSTALL_FULL_*DIR}` variables available but we are not using them for now since librime is still using custom `${LIB_INSTALL_DIR}` and `${BIN_INSTALL_DIR}`.

CMakeLists.txt: Ensure path in pkgconfig file to be absolute

---

CMakeLists.txt

[GNU/Hurd](https://hurd.gnu.org) has a `CMAKE_SYSTEM_NAME` of "GNU". Adding this name to the list of matches like Linux/FreeBSD/DragonFly since they are all unix-like. This fixes the build failure of librime in Debian under hurd-i386 architecture.

CMakeLists.txt: Add proper support for GNU/Hurd

---

src/rime/setup.cc
src/rime/setup.h
src/rime_api.cc
src/rime_api.h

feat(logging): setup min log level, log dir and file mode

---

README-mac.md

Fix `make xcode/release-with-icu` error
```
ld: library not found for -licudata
clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **
The following build commands failed:
Ld /Users/alswl/dev/myproject/squirrel/librime/build/lib/Release/librime.1.7.3.dylib normal
```
same issue:
[按照 "INSTALL.md" 尝试编译 squirrel，执行到 make deps 这一步时提示以下内容 不会编程，所以看不懂，希望有大佬帮我看看怎么回事 · Issue #544 · rime/squirrel](https://github.com/rime/squirrel/issues/544)
[After upgrade to Boost 1.75, compilation fails with ld: library not found for -licudata · Issue #67427 · Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core/issues/67427)
Solution via https://github.com/Homebrew/homebrew-core/issues/67427#issuecomment-754187345:
```
export …
```

docs: add info about build with bottled icu4c

---

src/rime/candidate.h
src/rime/gear/simplifier.cc
src/rime/gear/simplifier.h

by adding "allow_erase_comment" argument
Fixes #
Allow simplifier to return empty comment. There are situations that I want simplifier to erase comment and return empty comment. For example in emoji conversion, I don't want converted emoji to have readings from reverse_look_up filter.

Allow simplifier to return empty comment

---

src/rime_api.cc
src/rime_api.h
tools/rime_api_console.cc

enable the frontend to display a message when an arbitrary option defined in the
schema is updated.
Closes #447
the option name eg. ascii_mode is passed to the notification handler function,
there, get_state_label gives IME frontend the access to the human readable label
for the current state of the option defined in *.schema:/switches/@*/states.
when selection is changed in a radio group, more than one option in the group is
updated so it only returns a non-empty label while querying the selected option.
Fixes #

feat(api): get_state_label returns the state label for UI display

---

src/rime/switches.cc

Fix regression issue in commit: 5e8aca2756eed71b65ec821c1bf18d10d10fc25b
```
trime/app/src/main/jni/librime/src/rime/switches.cc:117:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
}
^
1 error generated.
```
We can add more compiler option in CI to avoid issue like this.
Fixes #

fix: fix missing control paths issue

---

CMakeLists.txt
build.bat

I built librime on Windows Dev Kit 2023.
My `env.bat`:
```bat
rem Customize your build environment and save the modified copy to env.bat
set RIME_ROOT=%CD%
set BOOST_ROOT=[local git repo of boost]
rem REQUIRED: path to Boost source directory
if not defined BOOST_ROOT set BOOST_ROOT=%RIME_ROOT%\deps\boost_1_76_0
rem OPTIONAL: architecture, Visual Studio version and platform toolset
set ARCH=ARM64
set BJAM_TOOLSET=msvc-14.3
set CMAKE_GENERATOR="Visual Studio 17 2022"
set PLATFORM_TOOLSET=v143
rem OPTIONAL: path to additional build tools
rem set DEVTOOLS_PATH=%ProgramFiles%\Git\cmd;%ProgramFiles%\CMake\bin;C:\Python27;
```
Steps in a ARM64 Native Tools Command Prompt for VS 2022 Preview:
```batch
build.bat boost_arm64
build.bat deps
build.bat librime
```
2. …

Support native build on win arm64

---

src/rime/gear/charset_filter.cc

See also: 
[CJK Unified Ideographs Extension H](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs?section=39#CJK_Unified_Ideographs_Extension_H)
[Other CJK ideographs in Unicode, not Unified](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs?section=39#Other_CJK_ideographs_in_Unicode,_not_Unified)

fix(charset_filter): Update `is_extended_cjk` to compatible with Unicode 15.

---

data/minimal/cangjie5.schema.yaml
data/minimal/luna_pinyin.schema.yaml
src/rime/gear/switch_translator.cc
src/rime/gear/switch_translator.h
src/rime/switcher.cc
src/rime/switches.cc
src/rime/switches.h
src/rime_api.cc
src/rime_api.h

Fixes #
YAML config: a switch can have optional string array `abbrev` to define
short state labels which do not have to take the first character of the
full state labels.
(switch_translator): folded options now make use of the short labels
defined in the `switches` configuration.
(rime_api): add function `get_state_label_abbreviated`, which returns
`RimeStringSlice` type since the short label can be the first character
of the full label string.

feat(switches): abbreviate state labels

---

README.md

Fixes #
iRime stopped updating source code long time ago, so the version on App Store is proprietary.
Instead, Hamster is real open source and becoming popular.

Replace iRime with Hamster [skip ci]

---

.gitignore
src/rime/dict/dict_compiler.cc
src/rime/dict/entry_collector.cc
src/rime/dict/entry_collector.h
src/rime/dict/table.cc
src/rime/dict/table.h
src/rime/dict/vocabulary.cc
src/rime/dict/vocabulary.h
test/table_test.cc

Fixes #583 
Use several techniques to try to save the memory consumption when compiling dictionaries.
This may save about 30% memory consumption.
Tested schema: [rime-ice](https://github.com/iDvel/rime-ice)

Tweak to Save Memory Consumption When Compiling Dictionaries

---

src/rime_api.cc
src/rime_api.h

Fixes #
Upstream a patch. Similar with #597, I need these APIs but don't want to use `rime_get_api`.

(api): expose candidate operation apis

---

src/rime/algo/encoder.cc
src/rime/algo/strings.cc
src/rime/algo/strings.h
src/rime/algo/utilities.cc
src/rime/dict/entry_collector.cc
src/rime/dict/entry_collector.h
src/rime/dict/vocabulary.h

Fixes # N/A
This PR uses several techniques to try to improve the speed of compiling dictionaries. It may save 8 ~ 10 % of build time of the dictionaries.
Tested schema: [rime-ice](https://github.com/iDvel/rime-ice)
Compiler: GCC 13.1.1
OS: Arch Linux x86_64
`(Script)Encoder::DfsEncoder` takes about 53% of the build time to run before the optimization.
By speeding up `EntryColletor::TranslateWord`, `(Script)Encoder::DfsEncoder` takes about 45% of the build time to run, about 8% shorter than before.

Attemp to Improve Dict Complile Performance

---

src/rime/dict/dict_compiler.cc
src/rime/dict/entry_collector.cc

Fixes # N/A
Recude Memory Comsumption When Compiling Dictionaries. Yes, again.

Recude Memory Comsumption When Compiling Dictionaries (2)

---

CMakeLists.txt
src/rime/deployer.cc

Upstream a [patch](https://github.com/LibreService/my_rime/blob/a42f35e08b45120a082c1a95d33877cff55a9af1/librime_patch#L13-L24) to a CMake option.
This is necessary for deploying in wasm. Ref: https://github.com/emscripten-core/emscripten/issues/8988

allow single thread deployment

---

CHANGELOG.md
doc/Doxyfile
include/darts.h
src/rime/algo/calculus.h
src/rime/algo/syllabifier.cc
src/rime/candidate.h
src/rime/config/legacy_preset_config_plugin.cc
src/rime/dict/corrector.cc
src/rime/dict/dictionary.cc
src/rime/dict/level_db.cc
src/rime/dict/text_db.cc
src/rime/dict/user_db_recovery_task.cc
src/rime/dict/user_dictionary.cc
src/rime/gear/abc_segmentor.cc
src/rime/gear/ascii_composer.cc
src/rime/lever/deployment_tasks.cc
src/rime/lever/user_dict_manager.h
src/rime/switches.h
src/rime_api.h

Found via `codespell -S data,*.js -L rime,te,teh,lamda,fo,ue,seh,vew`
Fixes #

doc: fix typos

---

src/rime/lever/deployment_tasks.cc

If a directory is being created by two threads at the same time, it is possible that one succeed while the other fails. This change the order of create & check, so no matter which thread create the directory first, it will always succeed in the end.
Fixes #

Fix a potential race condition of MaybeCreateDirectory

---

src/rime/dict/entry_collector.cc
src/rime/dict/entry_collector.h

Fixes #
There are many words, but for each word there aren't many representations. Using map is correct in algorithm but bad in this reality. Too many small rbtrees.
200MB less peak memory usage for building https://github.com/miounet/rime-kmm-big (3.1GB -> 2.9GB), tested with heaptrack twice.

perf: replace rbtree with vector of pair

---

src/rime/gear/simplifier.cc

Fixes #
under Windows, with weasel, user_dir and shared_dir encoded in CP_ACP ( depend on code page setting ), if opencc file in those paths with NONE ASCII code (for example with simplified Chinese Windows code page CP936, user_dir with chinese characters ), it will make opencc hanged.

fixed: opencc does not work under Windows, when opencc files in a path code page incompatible with UTF-8.

---

src/rime/gear/simplifier.cc

Fixes #652 
EDIT: the screenshot actually shows a clear bug 🤦‍♂️. See below for a corrected one.

follow opencc conversion chain

---

src/rime/dict/entry_collector.cc

Fixes #
The 3 fields are no longer used after `Finish()`.
800MB less peak memory usage for building https://github.com/miounet/rime-kmm-big (2.9GB -> 2.1GB), tested with heaptrack.

perf: release memory of temporary fields

---

CMakeLists.txt
build.bat
deps/CMakeLists.txt

Fixes #
* Drop the `BOOST_USE_CXX11` cmake option as it's 2023.
* Fix cmake warning of wrong command order.
* Fix cmake warning of `project` missing. This is not tested here because linux ci uses system library and windows/macos ci caches dependencies, but I tested locally with My RIME.

drop BOOST_USE_CXX11; fix 2 cmake warnings

---

.github/workflows/macos-build.yml
.github/workflows/windows-build.yml
README-mac.md
env.bat.template
env.vs2019.bat
env.vs2022.bat
install-boost.bat
install-boost.sh

Fixes #
1.78 is a bit old. When I build librime with clang on Windows, clang 15 produces tons of warning, and clang 16 refuses to build.

upgrade boost to 1.83

---

CMakeLists.txt
src/rime/lever/customizer.cc
src/rime/lever/deployment_tasks.cc

Build failed on Trime procject with boost 1.83.0
```
/trime/app/src/main/jni/librime/src/rime/lever/customizer.cc:91:11: error: 'copy_file' is deprecated: Use copy_options instead of copy_option [-Werror,-Wdeprecated-declarations]
```

Fix build error of deprecated api

---

src/rime/dict/mapped_file.cc

Fixes #
Don't ~reinvent~ copy wheels.

use boost::filesystem::resize_file

---

src/rime/gear/reverse_lookup_filter.cc
src/rime/gear/reverse_lookup_filter.h

None
Allows `reverse_lookup_filter` to append new information to existing comments, instead of just ignoring or overwriting them. Before this PR, the user has to discard some information when the comment and the new codes are not empty.
This PR introduces a new option `append_comment`, akin to the existing `overwrite_comment`.
- If `append_comment` is `true`, the newly found codes are appended to the existing comments (separated with a space). 
- If both `append_comment` and `overwrite_comment` are true, `overwrite_comment` takes priority, ie. the existing comments are discarded.
Not sure where to put the test? I'd be happy to add tests, should there be any guidance.
4. Can be merged clean …

feat: Allow reverse_lookup_filter to append new codes to existing comments

---

src/rime/gear/reverse_lookup_filter.cc

Reported by @eagleoflqj ; Fix a regression introduced by #699 
#699 mistakenly assumed at least one of `append_comment` and `overwrite_comment` is true, and will break the old behavior. This PR fixes this.
Sorry for my mistake :(

Fix a regression in reverse_lookup_filter introduced in #699 

---

.github/workflows/windows-build.yml
build-clang.bat
src/rime/algo/encoder.h
src/rime/composition.h
src/rime/config/config_types.h
src/rime/context.h
src/rime/deployer.h
src/rime/dict/corrector.h
src/rime/dict/db.h
src/rime/dict/dictionary.h
src/rime/dict/level_db.cc
src/rime/dict/text_db.h
src/rime/dict/user_db.cc
src/rime/dict/user_db.h
src/rime/dict/vocabulary.h
src/rime/gear/simplifier.cc
src/rime/lever/deployment_tasks.h
src/rime/lever/user_dict_manager.h
src/rime/resource.h
src/rime/service.h
src/rime/setup.cc
src/rime/setup.h
src/rime/translation.h
tools/CMakeLists.txt

Fixes #
To support mingw build and test, added tons of `RIME_API`. By the way enabled building full rime tools on Windows.

support mingw-w64 build on windows

---

.github/workflows/macos-build.yml

Fixes #
Before: [release CI](https://github.com/rime/librime/actions/runs/6064923382/job/16453870343) for https://github.com/rime/librime/commit/9e9141864fc5a63e8738d5f994cea7c976f080af
boost's locale isn't built under Apple Clang 14.
After: [release CI](https://github.com/rime/librime/actions/runs/6067082076/job/16458343630) for https://github.com/rime/librime/commit/37d6e922d3c161b2ccf59fc208246089395a833d
boost's locale is built under Homebrew Clang 16.
These behaviors are the same in my local macOS x64 13.5.1

ci: use clang 16 for macOS

---

README-windows.md
README.md
build-clang.bat

Fixes #
Simply add the build target for charcode plugin.
Before: [release CI](https://github.com/rime/librime/actions/runs/6064923382/job/16453870294) for https://github.com/rime/librime/commit/9e9141864fc5a63e8738d5f994cea7c976f080af
After: [release CI](https://github.com/rime/librime/actions/runs/6068513313/job/16461568173) for https://github.com/rime/librime/commit/024651cfbf567f1a24f1394fbafbca86e131a70c

ci: build boost::locale for charcode in clang win

---

src/rime/dict/table.cc
src/rime/dict/table.h
tools/CMakeLists.txt
tools/rime_table_decompiler.cc

tools: add rime_table_decompiler

---

.github/workflows/commit-ci.yml
.github/workflows/docker-build.yml
.github/workflows/linux-build.yml
.github/workflows/macos-build.yml
.github/workflows/windows-build.yml
Dockerfile

rewrite Dockerfile to include plugins

---

tools/codepage.h
tools/rime_api_console.cc
tools/rime_console.cc
tools/rime_deployer.cc
tools/rime_dict_manager.cc
tools/rime_patch.cc
tools/rime_table_decompiler.cc

Fixes #
for Windows, SetConsoleOutputCP(CP_UTF8) and restore CP_ACP before exiting.

update tools: code page switching for windows

---

src/rime/setup.cc
src/rime_api.h

Fixes #727
Before:
If `app_name` not provided, only log to stderr, `min_log_level` doesn't work at all.
If `app_name` provided, log to both stderr and file (if `log_dir` not provided, use temporary dir).
After:
If `app_name` provided and provide `log_dir` as empty string, log only to stderr with `min_log_level` working.

allow only logging to stderr with minloglevel

---

.github/workflows/windows-build.yml
Makefile
build-clang.bat
build.bat

Fixes # N/A
Run ctest command to run the test program, so we don't have to look for the binaries.

Run ctest to run the test program

---

src/rime/lever/deployment_tasks.cc

Fixes #726
* If log disabled or only log to stderr, do not perform clean.
* Otherwise, respect log_dir instead of always searching temporary directories.

CleanOldLogFiles respects log_dir

---

src/rime/lever/deployment_tasks.cc

CleanOldLogFiles doesn't scan cwd when no log_dir

---

build.bat
deps.mk

Fixes #
Use designated build directory

Use designated build directory for glog

---

src/rime/context.h
src/rime/dict/mapped_file.h
src/rime/dict/string_table.h
src/rime/segmentation.h
src/rime/service.h
src/rime/translation.h

export symbols for librime-predict

---

.github/workflows/release-ci.yml
Dockerfile
README.md
tools/rime_api_console.cc

support predict plugin

---

data/minimal/default.yaml
src/rime/gear/key_binder.cc

the new condition `when: predicting` allow paging key binding to comma, period keys to be disabled when the active menu has tag `prediction`.
it's used with the `predictor` component in the librime-predict plugin. see updates in data/minimal/default.yaml for example configuration.

feat(key_binder): add `when: predicting` condition

---

plugins/plugins_module.cc
src/rime/algo/utilities.cc
src/rime/config/config_data.cc
src/rime/dict/mapped_file.h
src/rime/dict/string_table.cc
src/rime/dict/user_db.cc
src/rime/gear/shape.cc
src/rime/key_event.cc
src/rime_api.cc
test/config_compiler_test.cc

Fixes # N/A
Continue to Migrate from Boost to std

Continue to Migrate from Boost to std

---

src/rime/algo/encoder.cc
src/rime/algo/strings.cc
src/rime/algo/strings.h

fix: correct the split behavior during collecting dict entries

---

src/rime/engine.cc
tools/rime_api_console.cc

allow zero-length segment to be translated.
add `placeholder` tag to the segment to prevent it from being trimmed.

feat(engine): translate zero-length prediction

---

src/rime_api.cc
src/rime_api.h

新增 api 用于调整用户已输入的字符。
resolve #547

feat(rime_api): add RimeApi::set_input

---

.github/workflows/macos-build.yml
.github/workflows/windows-build.yml
README-mac.md
build.bat
env.bat.template
env.vs2019.bat
env.vs2022.bat
install-boost.bat
install-boost.sh

upgrade boost to 1.84.0 and replace jfrog

---

src/rime/setup.cc

`FLAGS_logtostderr` works fine on desktop environments, but on Android, it does not write to logcat, and requires to have a valid `log_dir` in order to write log files as well as logcat. 
https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/src/logging.cc#L809 (only `LogDestination::MaybeLogToStderr` can write to logcat on Android)
https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/src/logging.cc#L1840 (if `FLAGS_logtostderr` is set, the branch above cannot be reached)
`google::LogToStderr()` makes the log only goes to stderr on desktop, and logcat on Android.
https://github.com/google/glog/blob/b33e3bad4c46c8a6345525fd822af355e5ef9446/src/logging.cc#L727-L734
I only tested it on Android, maybe further testing is needed.
1. Unit and manual …

make sure glog only write to stderr using google::LogToStderr()

---

src/rime/lever/deployment_tasks.cc

Fixes #
less nest when filesystem iteration in CleanOldLogFiles::Run(Deployer* deplyer) for better performance. esp under Windows with log dir %TEMP% and too much files inside that directory.
simple test code, target iteration folder `./files` with 1 million files. compiled with command
`g++ -Wall iterator.cpp -std=c++17 -o iterator`
```cpp
#include <chrono>
#include <iostream>
#include <filesystem>
#include <vector>
using namespace std;
namespace fs = std::filesystem;
int main()
{
auto start = …
```

perf: less nest in filesystem iteration When CleanOldLogFiles::Run

---

src/rime/gear/chord_composer.cc
src/rime/gear/chord_composer.h

Stop composing chord when a key event is super or caps modified, just like ctrl, alt, and shift.
Currently, super+any key will be consumed by rime when chord typing.
Type `super+a` the raw sequence will be cleared and the key can be forwarded to the client application.

fix: chord_composer should stop at super and caps by default

---

src/rime/gear/simplifier.cc

Fixes #652 , improves #688 
Improve chain conversion #688 . Specifically, this PR corrects the mistake that chain conversion only converts EXACT matched string while ignoring partially matched conversions.
E.g. previously, the exact matching results in `才能 (zh-Hans) -> 才能 & 纔能 (zh-Hant) -> 才能 & 纔能 (zh-TW, zh-HK)`, because it starts with exactly-matched `才能 (zh-Hans) -> 才能 & 纔能 (zh-Hant)`, then ignores the partially-matched rule of `纔 (zh-Hant) -> 才 (zh-TW, zh-HK) `. Now the conversion can get the correct result: `才能 (zh-Hans) -> 才能 & 纔能 (zh-Hant) -> 才能 (zh-TW, zh-HK)`
5. PR will be merged by rebase …

chain conversion

---

.github/workflows/commit-ci.yml
Makefile
plugins/plugins_module.cc
sample/src/sample_module.cc
sample/src/trivial_translator.cc
sample/src/trivial_translator.h
sample/test/trivial_translator_test.cc
sample/tools/sample_console.cc
src/rime/common.h
src/rime/dict/table.h
test/algebra_test.cc
test/component_test.cc
test/config_compiler_test.cc
test/config_test.cc
test/corrector_test.cc
test/dictionary_test.cc
test/key_event_test.cc
test/prism_test.cc
test/resource_resolver_test.cc
test/rime_test_main.cc
test/syllabifier_test.cc
test/table_test.cc
tools/rime_table_decompiler.cc

Fixes #
Apply clang format in rime source code.
Add targets in Makefile, to format code, just use command.
```
make clang-format-apply
```

Apply clang format in rime source code

---

.github/workflows/macos-build.yml
.github/workflows/windows-build.yml

Fixes #
**The `@actions/artifact` was kept `v3` due to breaking change.**
https://github.com/actions/upload-artifact
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.
This will dismiss the warning of deprecated Node.js 16
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/cache@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
1. Unit and …

ci: upgrade github action to v4

---

src/rime/dict/dict_compiler.cc

Fixes #
Rebuild packs if the pack source dict file is updated, even if the primary table is not updated.
Previously, packs are only rebuilt after the primary table is rebuilt.
Tested with:
- no packs
- one pack, build successful, able to use words in the pack
- one pack, unmodified, won't rebuild
- one pack, remove source file, able to use the prebuilt table
- one pack, modified, can rebuild automatically
- multiple packs, remove one source file, the other can still be used
- multiple packs, only modified pack gets rebuilt
- modified primary dict, all packs will be rebuilt except those lacking source files (I'm not sure if this is safe, but the current design of dictionary packs is also vulnerable to this kind of problem.)
1. Unit and …

feat(dict_compiler): rebuild packs on demand

---

.git-blame-ignore-revs

Fixes #
The extensive changes can be hidden from the blame view using Git's git blame --ignore-revs-file configuration setting.

Add blame ignore file

---

src/rime/dict/tsv.cc

chore: log file_path_ when warning in tsv.cc

---

src/rime/context.cc
src/rime/context.h
src/rime/gear/editor.cc
src/rime/gear/navigator.cc
src/rime/gear/speller.cc

call Context::BeginEditing when input is edited after selection. move cursor also counts as edit.
the tag is used to tell if BackSpace should delete the last input character or revert a recent selection.
the information was previously denoted by kConfirmed status which caused the side-effect of breaking a user phrase into individual segments.
fixed #746, fixed #830

fix(context): tag selected segment after editing

---

src/rime/dict/dictionary.cc
src/rime/dict/dictionary.h
src/rime/dict/user_dictionary.cc
src/rime/dict/user_dictionary.h
src/rime/dict/vocabulary.h
src/rime/gear/script_translator.cc
src/rime/gear/translator_commons.h

feat: predict words longer than 4 syllables

---

src/rime/lever/deployment_tasks.cc

fix(glog): no read permission on the cwd on Android

---

.github/workflows/windows-build.yml
CMakeLists.txt
README-windows.md
plugins/CMakeLists.txt
plugins/plugins_module.cc
src/CMakeLists.txt

in cmake config set RIME_PLUGINS_DIR as relative to libdir
Fixes #

fix(plugins): load plugins in relative path

---

src/rime/deployer.h
src/rime/lever/deployment_tasks.cc
src/rime/setup.cc

- close rime/home#1484
- avoid deleting incorrect files, some cases like rime.lua with rime_api_console

set log filename extension and avoid deleting incorrect files

---

src/rime/gear/chord_composer.cc
src/rime/gear/chord_composer.h

Fixes #
`chord_composer/finish_chord_on_first_key_release: {bool}`
default `false`, if set `true`,  tested in rime_api_console :

add param `chord_composer/finish_chord_on_first_key_release` for chord_composer, first release to finish chord

---

src/rime/gear/chord_composer.cc
src/rime/gear/chord_composer.h

Fixes #
with #828 `chord_composer/finish_chord_on_first_key_release: true`, the left keys of previous chord, may be inserted
to the new chord.
test procedure (`combo_pinyin`):
1.  press `w` `l` , get `ce` not finishchord
2. release `l`, get `ce` finishchord, `w` saved to the prev_pressed_
3. hold the `w` key, system may resend keydown event of `w`, as it still in the prev_pressed_, it will not be insert to new chord pressed_
4. press `s` `d` `j`, get `shi` not finishchord
5. the held `w` will repeat keydown event, will still be ignored.
6. release `d`, finish current chord, save `sj` to prev_pressed_(with `w` deleted), repeat the new loop on and on.
3. At …

fix(chord_composer): ignore repeated keys

---

src/rime/config/config_component.cc
src/rime/config/config_component.h
src/rime/config/config_data.cc
src/rime/config/config_data.h
src/rime/context.cc
src/rime/engine.cc
src/rime/switcher.cc
src/rime/switcher.h

the issue is mentioned here https://github.com/rime/librime/issues/818#issuecomment-1986713080
let `Switcher` object live across schema switching.
restore saved options only after input session is created.
save options on schema switching as before, but called explicitly.

fix(switcher): superfluously load saved options

---

cmake/AddRCInfo.cmake
src/CMakeLists.txt
src/rime.rc

build: add resource info for windows MSVC build

---

cmake/AddRCInfo.cmake
src/CMakeLists.txt
src/rime.rc

Fixes #
nightly build clang output
release build librime.dll

build: add English resource info for mingw/clang build.

---

.github/workflows/commit-ci.yml
src/rime/algo/encoder.cc
src/rime/dict/dict_compiler.cc
src/rime/dict/entry_collector.cc

Fixes #
Format code with clang-format 18.1.
**It's hard for Homebrew to pin or install the older version formula.**
Maybe we can use other solution to install specific clang-format version?

Format with clang-foramt 18.1

---

src/rime/algo/syllabifier.h
src/rime/gear/script_translator.cc

Previously, the correction count limit doesn't really work, and it will take all candidates. When finding the candidates for the last page, ScriptTranslation::PrepareCandidate can return nullptr, leading to segfault.
Fixes #

fix(script_translator): correction can cause segfault

---

.gitignore
src/rime/context.cc

Fixes #
Add parameter check for index < 0 for Context::Highlight
To prevent crash if index < 0
Also added git ignore for plugin and Mac DS_Store file

Add parameter check for index < 0 for Context::Highlight

---

src/rime/gear/speller.cc

Previously, the speller only auto-selects Phrases (type "table" and "user_table"), and does not select SimpleCandidate, but history_translator only produces SimpleCandidate, and thus history candidates cannot be auto-selected. This PR corrects this oversight.
(`history_translator` will preserve the old candidate type, e.g. "uniquified", but we cannot access the genuine candidate via SimpleCandidate here, unfortuantely.)
Fixes #

fix(speller): make simple candidates auto-selectable

---

README.md

docs: add zsh-rime

---

.github/workflows/linux-build.yml
README.md
src/rime/setup.cc

Fixes #
Prevent initializing glog twice by using an API that is available in glog 0.7

prevent initializing glog twice

---

src/rime/algo/encoder.cc
src/rime/dict/dict_compiler.cc
src/rime/dict/entry_collector.cc
src/rime/dict/entry_collector.h

chore: log dict file info and line number info when deploying warning

---

.github/workflows/release-ci.yml
src/rime/gear/matcher.cc
src/rime/gear/recognizer.cc
src/rime/gear/recognizer.h

recognizer  matcher 增加 @name_space 
用於  patterns 有重疊時， 可以調整優先順序
```yaml
engine/processors:
- recognizer
- recognizer@recognizer2
engine/segmentors:
- matcher
- matcher@recognizer2
recognizer: 
#import_preset: default
patterns: 
...
recognizer2:
import_preset: default 
Fixes #

Recognizer ns

---

src/rime/common.h
src/rime/context.cc
src/rime/context.h
tools/rime_api_console.cc

Previously, the two APIs will always delete the currently selected candidate, regardless of what its argument is.
Fixes #899 

fix(api): delete_candidate and delete_candidate_on_current_page

---

src/rime/gear/key_binder.cc
src/rime/lever/deployment_tasks.cc
src/rime/service.cc
src/rime_api_impl.h

Replace std::bind with lambda to increase readability

---

src/rime/common.h
src/rime/context.cc
src/rime/context.h

Fixes #
As in practice when both
```cpp
DeleteCandidate(size_t index)
```
and
```cpp
DeleteCandidate(std::optional<size_t> index)
```
exists, `DeleteCandidate({})` is translated to `DeleteCandidate(0)` at least for clang on macOS. 🌚

fix deleting current candidate

---

src/rime/lever/deployment_tasks.cc

Do not remove the symlinked log files, because they are still in use.
Fixes #902
Fixes https://github.com/rime/squirrel/issues/948
To verify this PR:
1. Restart Squirrel and see log files
2. Advance the system date by 1 day
3. Redeploy
- BEFORE: log files gone!
- AFTER: the current log file should be kept.

fix(deployment_tasks): do not remove log files in use

---

src/rime/gear/schema_list_translator.cc
src/rime/gear/switch_translator.cc
src/rime/switcher.cc
src/rime/switcher.h

fix(switcher): deactivate before setting option

---

src/rime/gear/speller.cc

#894 forgot to consider uniquified candidates but it should.
This fixes some more cases where the output of `history_translator` cannot be auto-selected.

fix(speller): consider genuine simple cands when auto select

---

src/rime/lever/deployment_tasks.cc

Fixes # N/A
We now use `google::LogToStderr()` instead of `FLAGS_logtostderr`, thus when not specify log dir on RimeTraits, `FLAGS_log_dir` must be empty, so use it to judge instead. 

fix(deployment_tasks): do not clean up log when not specify log dir

---

src/rime/gear/key_binder.cc

Fixes #
make the warning information more useful when parsing errors happen.

chore: more detail log info when key_binder/bindings parsing errors happen

---

CMakeLists.txt
Makefile

FreeBSD and OpenBSD typically use /usr/local as the prefix. This patch modifies the prefix.

Fix prefix for FreeBSD, OpenBSD

---

Makefile
deps.mk

On systems where nproc is not available, it will leave only -j which causes unlimited parallelism.
Note: macos CI build already uses ninja which properly handles parallelism.
Fixes #856 

fix(build): limit default parallelism to 8 cores

---

README.md

sort the order of community to keep same as official
Order: TUI, GUI, Web
Maybe a wiki like https://github.com/osfans/trime/wiki/Rime前端汇总 will be better to edit?

docs: add more frontends

---

src/rime/gear/ascii_composer.cc

Fixes #935
- In fcitx5, set 切换启用/禁用输入法 to Ctrl+Shift_L, remove Shift_L from 临时在当前和第一个输入法之间切换
- Use a schema that uses Shift_L to toggle ascii mode
- Increase the 500ms limit to 5000ms
- Use Ctrl+Shift_L to switch from rime to keyboard-us
- Press Ctrl, press Shift_L, release Ctrl, release Shift_L within 5s
- master behavior: switch from keyboard-us to rime ascii mode, pr behavior: switch from keyboard-us to rime normal mode

fix fcitx5 Ctrl+Shift switches to rime and toggles ascii mode

---

src/rime/gear/script_translator.cc
src/rime/gear/table_translator.cc
src/rime/gear/translator_commons.cc
src/rime/gear/translator_commons.h
src/rime/segmentation.h

Allow script_translator and table_translator to take multiple tags.
```
translator:
tags: [abc, tag1, tag2, tag3]
```
To keep compatibility:
1. if there is only `tag`: tags is set to that tag
2. if there is only `tags`: tags is set to that list
3. if there are both `tag` and `tags`: tag is the first element in the list, and `tags` is understood similar to `extra_tags`
5. GitHub Action CI pass
6. At least one contributor reviews and votes
7. Can be merged clean without conflicts
8. PR will be merged by rebase upstream base

feat(translator): allow a translator to take multiple tags

---

src/rime/setup.cc

Fix an issue where the symlink of log files are names as `UNKNOWN.INFO`, `UNKNOWN.WARNING`, or `UNKNOWN.ERROR`

fix log files named as UNKNOWN

---

src/rime/dict/user_dictionary.cc
src/rime/dict/user_dictionary.h

Essentially adding a cache for `table_->GetSyllableById`.
Before:
After:

Optimize user dictionary lookup performance

---

src/rime/common.h

Fixes # N/A
The latter has considerable performance improvement compared with the former.

perf(common): replace std unordered container with boost's

---

src/rime/context.cc
src/rime/context.h

regression: delete candidate of any index

---

src/rime/gear/navigator.cc
src/rime/gear/navigator.h

The cached spans can be wrong if not invalidated after selection. 
Consider: aabbccdd which can be understood as both 'aa'bb'cc'dd' and 'aab'bcc'dd'.
Suppose the first candidate is from 'aa'bb'cc'dd'. Now do {Control+Right}{Right}{Space} to select the first candidate of aab. Now do {Control+Right} again:
+ Expected: [aab]bcc|dd
+ Actual: [aab]b|ccdd (| is the caret)
This is because the spans are not recomputed even if we have picked a specific kind of segmentation. This PR adds a select handler and clears the spans to force the recomputation of the spans.
Fixes #
5. PR …

fix(navigator): wrong spans after selection

---

src/rime/gear/navigator.cc
src/rime/gear/navigator.h

Apparently #952 is flawed. This PR corrects some crashes reported by fcitx and squirrel users.

fix(navigator): notifier connection should be disconnected

---

tools/rime_api_console.cc

`synchronize` will destroy previous sessions, and make future commands unusable.
Fixes #

fix(rime_api_console): recreate session when necessary

---

src/rime/gear/punctuator.cc
src/rime/gear/punctuator.h

use ascii punctuation ,.:' after numbers.
they are auto-committed if followed by digit.
or commit manualy with space key.
double strike the key to access the original binding.

feat(punctuator): convert digit separators

---

src/rime/gear/gears_module.cc
src/rime/gear/simplifier.cc
src/rime/gear/simplifier.h

之前每创建一个 session，就会重复加载一遍 opencc，造成 session 初始化时卡顿，内存占用也会增加 10 MB 左右。如果有几十个 session，就会额外占用几百 MB 内存。
本 pr 为 opencc 增加了缓存机制，避免重复加载。

feat(simplifier): cache opencc

---

src/rime/gear/punctuator.cc

Follow-up #973 
Fix #972 (comment)
在数字分隔符后按空格，直接输出半角符号 **和一个空格** ，从而保持旧版行为。

enhance(punctuator): commit on space after digit separators

---

.github/workflows/commit-ci.yml

ci: add workflow_dispatch for commit-ci
Fixes #
lint job might failed if the clang-format version of ci host changed.

ci: fix lint, always lint with clang-format 18.1.8

---

cmake/RimeConfig.cmake

This pull request is to fix a cmake warning while building [ibus-rime](https://github.com/rime/ibus-rime). Please check out [CMake Warning - The package name passed to find_package_handle_standard_args (PkgConfig) does not match the name of the calling package (Rime)](https://github.com/rime/ibus-rime/issues/199) for more details.

fix(cmake): replace include() with find_package() to avoid calling find_package_handle_standard_args() twice with different arguments

---

src/rime/deployer.cc
src/rime/deployer.h
src/rime/lever/deployment_tasks.cc

虽然可以理解 `backup_config_files` 最初的目的，但目前的生态下，该功能已经没有什么作用了。
1. 它并不备份 lua 和 opencc 配置，所以备份得到的配置可能是不能用的
2. 它会直接覆盖掉之前的配置，不能避免误操作，所以还是无法给人放心的感觉
3. 拖慢「同步」速度
大部分讲究的用户会用 Plum/Git 等管理配置，再单独「同步」用户词库。这样 `backup_config_files` 就完全没有用了。而不讲究的用户可能本来就不知道这里有备份。
本 PR 在 installation.yaml 中增加一笔 `backup_config_files` 选项，置为 false 后则不再执行备份操作。 ~~默认值也直接改为 false。至于应否设为 true，还待商榷。~~ reverted, 默认保持原行为不变。

feat(deployer): allow disabling backup_config_files

---

src/rime/dict/dictionary.cc
src/rime/dict/dictionary.h
src/rime/gear/reverse_lookup_translator.cc
src/rime/gear/script_translator.cc
src/rime/gear/table_translator.cc
src/rime/gear/translator_commons.cc
src/rime/gear/translator_commons.h

closes #883 
该 PR 新增 `translator/dictionary_exclude`
```
translator:
dictionary: luna_pinyin
dictionary_exclude: 
- 零零
```
其语义严格等价于从 .dict.yaml 中删除对应词条，但不影响组句和用户词库，即用户依然可以选字打出对应词。在上面的例子中， luna_pinyin 在用户词库为空时，将无法输出「零零」，但用户可以依次选取2次「零」造词，之后又可以直接输出「零零」。
未解决问题：
- 是否应该使用外部 .txt 或 .dict.yaml 文件、而非 schema.yaml 来指定黑名单？

feat(translator_commons): add `dictionary_exclude` to exclude words

---

src/rime/gear/ascii_composer.cc

Fixes rime/ibus-rime#171
Recent version of GNOME inspect how input methods handle the Caps Lock key. If the key event is consumed by the input method, the desktop environment no longer toggles the Caps Lock state, which can lead to unexpected behavior.
This patch allows the Caps Lock key event to pass through the input method when `good_old_caps_lock` is enabled, restoring the expected toggle behavior.

fix(ascii_composer): Fix good old caps lock behavior

---

.github/workflows/commit-ci.yml

Windows Server 2019 has been retired. The Windows Server 2019 image has been removed as of 2025-06-30. For more details, see https://github.com/actions/runner-images/issues/12045
Fixes #

ci: update runner windows-2019 to windows-latest

---

src/rime/gear/memory.cc
src/rime/gear/memory.h
src/rime/gear/script_translator.cc
src/rime/gear/script_translator.h

feat(script_translator): learn new phrases automatically from segmentations
* separate new phrases by segmentations rather than using the sentence
as a whole, while committing into user\_dictionary
* join adjacent segments if the result is no longer than core\_word\_length
* ignore the phrases which are longer than max\_word\_length
在整句輸入時，通過斷句（由光標或選詞等產生）學習新詞，而不是學習整句作為新詞，然後寫入用戶詞典。
例如： 在下表中，句子中的符號‘|’，表示斷句的位置；且參數<code>max_word_length</code>和<code>core_word_length</code>，分別配置為7和4. 
| 學習的新詞 | 整句輸入時的斷句| 記錄的詞數  |
| ----- | -----------------------|------------ |
| 去畫    | 一旦嘗試\|去\|畫\|示意圖     |    3  |
| 和式    | 總是比把除數寫成\|和式\|要更方便些 |  2 （忽略 1）  |
| 它     | 它\|是我的一個東西          |   2   |
| 它     | 要做的就是簡化\|它          |   2   |
| 有歧義   | 這是\|有歧義\| 的一句話 |  3  |
| 他們是   | 我知道\|他們\|是\|可愛的人    |  3    | …

feat(script_translator): learn new phrases automatically from segmentations

---

src/rime/gear/script_translator.cc

Fix build error with Trime.
```
.../github/trime/app/src/main/jni/librime/src/rime/gear/script_translator.cc:269:1: error: non-void function does not return a value [-Werror,-Wreturn-type]
269 | }
| ^
1 error generated.
```

Fix non-void function does not return a value

---

.github/workflows/macos-build.yml

Use the macos-15 runner image
https://github.blog/changelog/2025-04-10-github-actions-macos-15-and-windows-2025-images-are-now-generally-available/

ci: use the macos-15 runner image

---

.github/workflows/commit-ci.yml

The forked repo non main branch won't trigger workflow, is hard for
preparing pull request on non main branch in forked repo.
First of all, we should trigger push event on any branch, the current
filter is wrong, which won't trigger workflow on **forked repo** push event.
The grammar is wrong by the document: https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#example-including-and-excluding-branches
> If you define a branch with the ! character, you must also define at least one branch without the ! character. If you only want to exclude branches, use branches-ignore instead.
Secondly, the main branch should trigger commit build in case of merge or rebase
with pull requests. …

ci: fix wrong filter on push event

---

.github/workflows/commit-ci.yml
action-install-clang-format.sh

Most of C++ developers prefer Unix box, so we should use the Unix for style check.
1. The lint time decrease from 1m 47s to 28s which is an improvement of 73.83%.
2. Upgrade clang-format is easier with one parameter.
3. llvm apt support Debian and Ubuntu distribution.
4. Improve CI waiting time for developer.

ci: use clang-format from apt llvm

---

README.md

ARIF 是一个轻量的输入法框架，目前支持 Readline 作为前端，Rime 作为引擎。
该项目最初是为了满足个人需求而开发，使用过程中逐渐完善，现已基本稳定。
希望能够给更多有类似需求的用户带来方便，故申请收录。

docs(README): add Readline frontend [skip ci]

---

src/rime/composition.cc

Fixes #
问题：在 editor 配置了 commit_script_text 后，触发该操作时 phony segment 的 input 会被一起输出出来
我发现在 GetPreedit 和 GetCommitText 中都对 phony 进行了过滤，也许在 GetScriptText 里也应该这样做？

fix(composition): skip phony segments in GetScriptText

---

src/rime/context.cc
src/rime/context.h
src/rime/service.cc

Fixes #
add a notifier `abort_notifier_` for Context, call it in`rime_api->clear_composition()` after Context::Clear(). esp for notifying session is clear by external API. 

feat: clear composition with a abortcomposition notification

---

.github/workflows/macos-build.yml

Fixes #
llvm/clang installed by homebrew  may be not abi compatable with system's stdc++ lib. it would cause `./install-boost.sh ` to fail.

ci(macos-13): use system llvm

---

src/rime/dict/vocabulary.cc

在编译 table 时，有时可以观察到 `sort: by_weight` 的词典中，重码候选顺序会因为排序不稳定而乱掉，改为稳定排序即可修复。

fix(vocabulary): Homophones sorting should be stable.
