rime/librime

README.md
src/lever/levers_module.cc

fix dangling pointers in RimeSchemaListItem
Add @osfans and trime

Add @osfans and trime

---

src/gear/simplifier.cc

Reference: [BYVoid/OpenCC #162] (https://github.com/BYVoid/OpenCC/pull/162)

Fix issue #64.

---

.travis.yml

[![Build Status](https://travis-ci.org/jakwings/librime.svg?branch=travis-ci)](https://travis-ci.org/jakwings/librime)
我想大致配置好了，還差用 rime_api_console 具體測試各種功能。
盡量用 apt-get 或 homebrew 安裝依賴。boost 具體用的是 iconv 還是 icu 沒研究清楚。
在 Ubuntu 下編譯 opencc 時遇到 `-fPIC` 相關錯誤，麻煩看一看：
https://travis-ci.org/jakwings/librime/builds/111425057
ping: #71

Add Travis CI configuration (resolve #71)

---

README.md
appveyor.install.bat
appveyor.yml

build without cache:
https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%2012
build with cache:
https://ci.appveyor.com/project/jakwings/librime/build/appveyor-ci%20build%2013

Windows: AppVeyor CI improvement

---

appveyor.install.bat

Responding to request from @osfans.

Upgrade libboost to 1.61.0 on AppVeyor CI build.

---

thirdparty/src/opencc/CMakeLists.txt
thirdparty/src/opencc/NEWS.md
thirdparty/src/opencc/README.md
thirdparty/src/opencc/data/CMakeLists.txt
thirdparty/src/opencc/doc/CMakeLists.txt
thirdparty/src/opencc/node/global.gypi
thirdparty/src/opencc/package.json
thirdparty/src/opencc/src/BinaryDict.cpp
thirdparty/src/opencc/src/CMakeLists.txt
thirdparty/src/opencc/src/Config.cpp
thirdparty/src/opencc/src/DartsDict.cpp
thirdparty/src/opencc/src/Dict.cpp
thirdparty/src/opencc/src/DictEntry.hpp
thirdparty/src/opencc/src/Exception.hpp
thirdparty/src/opencc/src/PhraseExtract.cpp
thirdparty/src/opencc/src/PhraseExtract.hpp
thirdparty/src/opencc/src/SimpleConverter.cpp
thirdparty/src/opencc/src/UTF8StringSlice.hpp
thirdparty/src/opencc/src/UTF8Util.hpp

Use OpenCC 1.0.4, with fixes that eliminate tons of warnings on Visual Studio 2015.

Upgrade OpenCC.

---

Makefile
Makefile.thirdparty
Makefile.xcode
appveyor.install.bat
build.bat
shell.bat

When using CMake to generate Makefiles, let CMake do all of build things for us.

Call cmake --build when possible.

---

README.md

https://github.com/jimmy54/iRime

docs(README): Add open source iRime frontend[ci skip]

---

src/rime/core_module.cc
src/rime/schema.cc
src/rime/schema.h
src/rime_api.cc

Fixes https://github.com/rime/librime/issues/140

fix(schema): create a "schema" component that opens Config by schema_id

---

src/rime/context.cc
src/rime/context.h
src/rime/engine.cc

feat(context): add property notifier

---

src/rime/dict/db.cc
src/rime/dict/dict_compiler.cc
src/rime/dict/dict_compiler.h
src/rime/dict/dictionary.cc
src/rime/dict/dictionary.h
src/rime/dict/mapped_file.h
src/rime/dict/preset_vocabulary.cc
src/rime/dict/prism.cc
src/rime/dict/reverse_lookup_dictionary.cc
src/rime/dict/reverse_lookup_dictionary.h
src/rime/dict/table.cc
src/rime/dict/table.h
src/rime/lever/customizer.cc
src/rime/lever/customizer.h
src/rime/lever/deployment_tasks.cc
tools/rime_deployer.cc

The current `master` code have serious issues introduced by using config compiler. This branch need to be merged as soon as possible.
But I think there are still an unresolved issue: how to detect that a resource file needs rebuild?
Cross-file references makes this more complicated than before.

Universal dictionary + no copying files to user directory

---

src/rime/config/build_info_plugin.cc
src/rime/dict/dict_compiler.cc
src/rime/lever/custom_settings.cc
src/rime/lever/deployment_tasks.cc

fix issues with the refactored config and dict_compiler

---

src/rime_api.cc
src/rime_api.h

based on https://github.com/rime/librime/pull/252/files, rebased to rime/librime@master and edited `rime_api.*` to resolve review comments.

feat(rime_api): get candidate list from index

---

src/rime/dict/dictionary.h
src/rime/gear/grammar.h
src/rime/gear/poet.cc
src/rime/gear/poet.h
src/rime/gear/script_translator.cc
src/rime/gear/script_translator.h
src/rime/gear/table_translator.cc
src/rime/gear/table_translator.h
src/rime/gear/translator_commons.cc
src/rime/gear/translator_commons.h

add inteface to grammar plugin; fall back to naive formula if missing "grammar" module

feat(grammar): compare homophones/homographs in sentence

---

src/rime/gear/key_binder.cc

To bind a key to a key sequence,
set 'send_sequence' attribute of a 'key_binder/bindings' entry.
Special named keys should be around with "{" and "}".
Notice that you have to add quotes when writing a filed with "{" or "}" in a
yaml file.
For example:
key_binder:
bindings:
- { when: composing, accept: a, send_sequence: aa }
- { when: composing, accept: Right, send_sequence: "{Right}{Right}" }
- { when: composing, accept: Left, send_sequence: "aa{Left}{Left}" }

feat(key_binder): bind key to a key sequence  [Closes #301]

---

README.md

add third-party frontend: emacs-rime

---

src/rime/gear/selector.cc
src/rime/schema.cc
src/rime/schema.h

i.e. Pressing space bar back to page 1 when reaching the last page of selection
setting item in schema: `menu/page_down_cycle: true`

feat(selector): page down cycle

---

src/rime/gear/charset_filter.cc

change charset_filter to support CJK Unified Ideographs Extension G

Support CJK Unified Ideographs Extension G in charset_filter

---

src/rime/candidate.h

Change two occurrences of `const string` to `const string&`.

chore(candidate.h): `type` should be a reference

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature-request.md
.github/pull-request-template.md

- doc: add issue template
- doc: add pull request template
Fixes #

Add issue and pull request template

---

.github/workflows/commit-ci.yml
.github/workflows/release-ci.yml

Bump github action to v3
Fixes #

Bump github action to v3

---

.github/workflows/commit-ci.yml
.github/workflows/macos-build.yml
.github/workflows/windows-build.yml

ci: fix CI on push to branch and pull request

---

.gitmodules

Replace module name with repo name
You can sync your `.gitconfig` with `git submodule sync`
Fixes #

chore: replace name of submodule with repo name

---

README.md

Update ci build badges.
Fixes #

Update ci build badges

---

src/rime/context.cc
src/rime/context.h
src/rime_api.cc
src/rime_api.h

This is a continuation of #556.
This feature supports deleting candidate at arbitrary index, which is useful for quick deleting.

feat: delete selected candidate

---

build.bat
src/rime/algo/syllabifier.cc
src/rime/dict/corrector.cc
src/rime/setup.cc
xcode.mk

Fixes #577 
Adapt for glog v0.6.0, see commit message for detail.

Adapt for glog v0.6.0

---

src/rime/dict/table.h

remove unused include

---

.github/workflows/linux-build.yml

Fix clang job

---

README.md

chore: upgrade gtest to 1.14.0 

---

.github/workflows/windows-build.yml

ci: upload clang/mingw artifact with plugins

---

.github/workflows/windows-build.yml

fix mingw ci ran librime-lua

---

src/rime/deployer.cc

Fixes #
Upstream a patch from My RIME.
On 32-bit weasel will output an error log (bad allocation).

catch deployment failure (usually oom)

---

src/rime/engine.cc

修复使用多种translator共用的方案时日志频繁输出XXX made a futile translation问题

---

CMakeLists.txt
src/rime/config/build_info_plugin.cc

allow deployment without timestamp

---

src/rime/engine.cc
src/rime/gear/schema_list_translator.cc

Fixes https://github.com/fcitx/fcitx5-rime/issues/76

write user.yaml on RimeSelectSchema

---

tools/rime_api_console.cc

feat: add reload command for rime_api_console

---

.github/workflows/linux-build.yml
action-install-linux.sh

linux ci: don't build gtest and opencc

---

src/rime/common.h
src/rime/config/config_types.cc
src/rime/deployer.h
src/rime/dict/entry_collector.cc
src/rime/dict/preset_vocabulary.cc
src/rime/dict/reverse_lookup_dictionary.cc
src/rime/dict/table_db.cc
src/rime/dict/user_db.cc
src/rime/dict/user_db_recovery_task.cc
src/rime/dict/user_dictionary.cc
src/rime/gear/key_binder.cc
src/rime/lever/customizer.cc
src/rime/lever/deployment_tasks.cc

Fixes # N/A
Replace some types of Boost with std's.

Replace some types of Boost with std's

---

.github/workflows/commit-ci.yml
.github/workflows/release-ci.yml

release nightly

---

src/rime/gear/shape.cc

Fixes #
This is a regression since #755

fix full shape

---

src/rime/dict/db_pool.h
src/rime/dict/db_pool_impl.h
src/rime/dict/reverse_lookup_dictionary.cc
src/rime/dict/reverse_lookup_dictionary.h

extract existing code to a utility class, to be re-used by librime-predict.

refactor: DbPool for managing shared db files

---

CMakeLists.txt

generate rime.pc on macOS

---

.github/workflows/macos-build.yml

add m1 macos ci

---

Dockerfile

ci: enable plugin librime-lua

---

build.bat
src/rime/context.cc
src/rime_api.cc
src/rime_api.h
test/CMakeLists.txt

DONE: ci: the `build.bat` script should return eror on test failure.
TODO: fix the unit test on Windows. (expected to fail after the fix in `build.bat`)
Fixes #

fix(build.bat): return error if unit test failed

---

src/rime/lever/deployment_tasks.cc

fix: crash by iteration on non-existing directory

---

src/rime/dict/user_dictionary.cc
src/rime/dict/vocabulary.cc
src/rime/dict/vocabulary.h
src/rime/gear/contextual_translation.cc
src/rime/gear/script_translator.cc

feat(script_translator): word completion from 2nd place

---

tools/CMakeLists.txt

build(rime_table_decompiler): static linking on windows

---

README.md

doc: add coc-rime

---

tools/rime_api_console.cc

add synchronize command in api console

---

src/rime/module.cc

fix: show module name in log instead of their address

---

src/rime/config/config_data.cc

chore: log error info with file path info, when YAML::LoadFile exception happens.

---

src/rime/config/config_data.cc

chore: don't log warning on nonexistent *.custom.yaml file

---

src/rime/context.h

提供 librime-lua 取得 options, propretys 中的狀態
Fixes #

get status of  options and properties

---

src/CMakeLists.txt

build: provide rime.pdb when MSVC build

---

Makefile

fix: unable to make install in termux, because of file system redirection

---

src/rime_api.h

chore(api): move inclusion of standard headers out of extern "C"

---

test/flavored_api_test.cc
test/rime_test_main.cc

Fixes #989
Fix the memory leaks in runing unit tests.

fix(test): memory leaks in unit tests

---

README.md

doc: add tmux-rime

---

README.md

Fixes #
- **docs: sort the community section**
- **docs: polish build guide section**

Sort the community section

---

src/rime/gear/selector.cc

fix: navigation actions should trigger `update_notifier`
